# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e6820eae-4cdd-4bff-afdf-0f9440a83810";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2b8e7023-0438-4795-97b7-15b19ce57411";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/2235-D2D5";
    fsType = "vfat";
  };

  fileSystems."/media" = {
    device = "/dev/disk/by-uuid/987ea223-35e2-4df7-bc39-1f0b43baaf2c";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/8ffa95d0-0fd6-415a-b51f-2f1d3ca6581f";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-1d407619a01a.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-21cc5fe40c29.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-8081ec6ebc71.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-e1dce4d18d0a.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno3.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno4.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth349a69d.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3c7ac35.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth425e305.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth7fca855.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8c8ea16.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth92575a3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
